fix issue #41
If a job is paused, when django tries to format the next run time, it receives None because it is paused.
This check displays the "(paused)" string in place of the next run time instead of causing AttributeError 'NoneType' object has no attribute 'strftime'